export const ROUTE_FAILURE_CODE = {
  PROXY_FAILURE: "PROXY_FAILURE",
  UPSTREAM_INVALID_JSON: "UPSTREAM_INVALID_JSON",
  UPSTREAM_INVALID_RESPONSE: "UPSTREAM_INVALID_RESPONSE",
} as const;

export const ROUTE_REPORTED_CODES = new Set<string>(
  Object.values(ROUTE_FAILURE_CODE)
);
