/**
 * 폴더 README → VitePress docs/modules/*.md 동기화
 *
 * VitePress `<<<` 는 코드 스니펫 import라 README가 코드 블록으로 보인다.
 * 이 스크립트로 README 본문을 일반 마크다운 페이지로 생성한다.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(__dirname, "..");
const DOCS_ROOT = path.join(PACKAGE_ROOT, "docs");

/** @type {{ out: string; src: string }[]} */
const DOC_MAPPINGS = [
  { out: "modules/protocol.md", src: "src/protocol/README.md" },
  { out: "modules/rpc.md", src: "src/rpc/README.md" },
  { out: "modules/client.md", src: "src/client/README.md" },
  { out: "modules/runtime/index.md", src: "src/runtime/README.md" },
  { out: "modules/runtime/dispatch.md", src: "src/runtime/dispatch/README.md" },
  { out: "modules/runtime/factory.md", src: "src/runtime/factory/README.md" },
  {
    out: "modules/runtime/socket-runtime.md",
    src: "src/runtime/socket-runtime/README.md",
  },
  { out: "modules/runtime/transport.md", src: "src/runtime/transport/README.md" },
  { out: "modules/react/index.md", src: "src/react/README.md" },
  { out: "modules/react/hooks.md", src: "src/react/hooks/README.md" },
  { out: "modules/react/lib.md", src: "src/react/lib/README.md" },
  { out: "modules/stomp.md", src: "stomp/README.md" },
  { out: "modules/workers/index.md", src: "workers/README.md" },
  { out: "modules/workers/scripts.md", src: "scripts/README.md" },
];

const GENERATED_HEADER = `<!--
  AUTO-GENERATED by scripts/sync-docs.mjs — do not edit.
  Source: {{SOURCE}}
  Run: yarn docs:sync
-->

`;

const LEGACY_MODULE_FILES = [
  "modules/runtime.md",
  "modules/react.md",
  "modules/workers.md",
];

async function syncDoc({ out, src }) {
  const sourcePath = path.join(PACKAGE_ROOT, src);
  const targetPath = path.join(DOCS_ROOT, out);
  const content = await fs.readFile(sourcePath, "utf8");
  const header = GENERATED_HEADER.replace("{{SOURCE}}", src);

  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, `${header}${content}`, "utf8");
  console.log(`synced ${src} → docs/${out}`);
}

async function main() {
  for (const legacy of LEGACY_MODULE_FILES) {
    const legacyPath = path.join(DOCS_ROOT, legacy);
    await fs.rm(legacyPath, { force: true });
  }

  for (const mapping of DOC_MAPPINGS) {
    await syncDoc(mapping);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
