export const LIGHTNING_CREATE_FORM_FIELD = {
  TITLE: "title",
  MIN_PERSONNEL: "minPersonnel",
  MAX_PERSONNEL: "maxPersonnel",
  LIGHTNING_TYPE: "lightningType",
  RECRUIT_END_TIME: "recruitEndTime",
  ADDRESS: "address",
  DETAIL_ADDRESS: "detailAddress",
  LOCATION_POINT: "locationPoint",
  TARGET: "target",
  TAG_LIST: "tagList",
} as const;

export const LIGHTNING_CREATE_STEP_FIELD = {
  SELECT_TYPE: [LIGHTNING_CREATE_FORM_FIELD.LIGHTNING_TYPE],
  SELECT_LOCATION: [
    LIGHTNING_CREATE_FORM_FIELD.ADDRESS,
    LIGHTNING_CREATE_FORM_FIELD.LOCATION_POINT,
  ],
  SELECT_TIME_AND_PERSONNEL: [
    LIGHTNING_CREATE_FORM_FIELD.RECRUIT_END_TIME,
    LIGHTNING_CREATE_FORM_FIELD.MIN_PERSONNEL,
    LIGHTNING_CREATE_FORM_FIELD.MAX_PERSONNEL,
  ],
  SELECT_TARGET: [LIGHTNING_CREATE_FORM_FIELD.TARGET],
} as const;
