export const CLIENT_API_ERROR_CODE = {
  NETWORK_ERROR: "NETWORK_ERROR",
  CLIENT_TIMEOUT: "CLIENT_TIMEOUT",
  INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",
  INVALID_RESPONSE: "INVALID_RESPONSE",
  INVALID_RESPONSE_SCHEMA: "INVALID_RESPONSE_SCHEMA",
} as const;

export const CLIENT_FETCH_TIMEOUT_ABORT_REASON = "timeout";
