export const CLIENT_API_ERROR_CODE = {
  NETWORK_ERROR: "NETWORK_ERROR",
  INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",
  INVALID_RESPONSE: "INVALID_RESPONSE",
  INVALID_RESPONSE_SCHEMA: "INVALID_RESPONSE_SCHEMA",
} as const;
